apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
spec:
  releaseName: nginx-ingress-controller
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: "4.0.9"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    controller:
      # Configures the controller container name
      containerName: controller
      # Configures the ports the nginx-controller listens on
      containerPort:
        http: 80
        https: 443
    kind: Deployment
    metrics:
      enabled: true
      port: 10254
    
    labels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/component: controller

    admissionWebhooks:
      annotations: {}
      enabled: true
      failurePolicy: Fail
      # timeoutSeconds: 10
      port: 8443
